package api_rest.zoologico.Models;

public enum EspecialidadeVeterinario {
    FELINOS,
    CANINOS,
    ANIMAIS_EXOTICOS,
    AVES_EXOTICAS,
    REPTILIANOS,
    SILVESTRES,
    ROEDORES,
    ANIMAIS_MARINHOS,
    ANIMAIS_DE_GRANDE_PORTE,
    ANIMAIS_DE_PEQUENO_PORTE,
    BOVINOS,
    EQUINOS,
    CAPRINOS,
    SUINOS,
    ANIMAIS_DE_ESTIMACAO,
    ANIMAIS_DOMESTICOS_NAO_CONVENCIONAIS,
    ANFIBIOS
}

